### PR TITLE
To do items - DO NOT MERGE

### PR DESCRIPTION
**Pull request by tuckermullen**
@bjblock - I can't seem to get a user_id assigned to my items when they're created. In turn, it won't display them. That is the only thing holding me back on this part of the project. When I check in the console, the items are being successfully created but the user_id is nil on all of the items. Thanks!

### CODE REVIEW

**Comment by tuckermullen** [comment]
I had commented out `before_filter authenticate!` which wasn't assigning the user_id to the items.

**Comment by bjblock** [comment]
A little confused because this is closed.  Is this fixed now?

**Comment by tuckermullen** [comment]
Yes, sorry! It was a stupid fix and I realized it shortly after posting the question.

**Comment by bjblock** [comment]
no worries.  just making sure.

**Pull request closed without merging**
